/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mintic.unal.redflix.vista;

import java.util.Optional;
import mintic.unal.redflix.RedFlixApplication;
import mintic.unal.redflix.SpringContext;
import mintic.unal.redflix.modelos.Pelicula;
import mintic.unal.redflix.repositorios.PeliculaRepositorio;
import mintic.unal.redflix.modelos.Serie;
import mintic.unal.redflix.repositorios.SerieRepositorio;

/**
 *
 * @author daniela
 */
public class Ventana extends javax.swing.JFrame {

   
    PeliculaRepositorio peliculaRepositorio;
    SerieRepositorio serieRepositorio;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        String [] args = {};
        RedFlixApplication.runSpringServer(args);
         
        //Con getBean puedo obtener objetos del mundo de Spring. En este caso: ObraRepositorio. 
        //Si quiero acceder a otro repositorio, tengo que crear un nuevo getBean
        peliculaRepositorio = SpringContext.getBean(PeliculaRepositorio.class);
        serieRepositorio = SpringContext.getBean(SerieRepositorio.class);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEjecucion = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btConsultarPel = new javax.swing.JButton();
        btGuardarPel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btEliminarPel = new javax.swing.JButton();
        tfPelTitulo = new javax.swing.JTextField();
        btLimpiarPel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPelDirector = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfAnio = new javax.swing.JTextField();
        tfPelId = new javax.swing.JTextField();
        btCrearPel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btConsultarSerie = new javax.swing.JButton();
        btGuardarSerie = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btEliminarSerie = new javax.swing.JButton();
        tfSerieTitulo = new javax.swing.JTextField();
        btLimpiarSerie = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfTemporadas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfEpisodios = new javax.swing.JTextField();
        tfSerieId = new javax.swing.JTextField();
        btCrearSerie = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAlignmentX(1.5F);
        jPanel1.setAlignmentY(1.5F);

        btConsultarPel.setText("Consultar película por id");
        btConsultarPel.setActionCommand("");
        btConsultarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarPelActionPerformed(evt);
            }
        });

        btGuardarPel.setText("Guardar");
        btGuardarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarPelActionPerformed(evt);
            }
        });

        jLabel2.setText("Pel Título");

        btEliminarPel.setText("Eliminar");
        btEliminarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarPelActionPerformed(evt);
            }
        });

        tfPelTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPelTituloActionPerformed(evt);
            }
        });

        btLimpiarPel.setText("Limpiar");
        btLimpiarPel.setToolTipText("");
        btLimpiarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarPelActionPerformed(evt);
            }
        });

        jLabel3.setText("Resumen");

        jLabel4.setText("Director");

        tfPelDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPelDirectorActionPerformed(evt);
            }
        });

        jLabel5.setText("Año");
        jLabel5.setToolTipText("");

        jLabel1.setText("id");

        btCrearPel.setText("Crear");
        btCrearPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearPelActionPerformed(evt);
            }
        });

        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResumen);

        jLabel8.setText("PELÍCULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfPelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPelDirector)
                            .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGuardarPel)))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfPelId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btCrearPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminarPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultarPel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpiarPel)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarPel)
                    .addComponent(btCrearPel)
                    .addComponent(btEliminarPel)
                    .addComponent(btLimpiarPel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(btGuardarPel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Película", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btConsultarSerie.setActionCommand("");
        btConsultarSerie.setLabel("Consultar serie por id");
        btConsultarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSerieActionPerformed(evt);
            }
        });

        btGuardarSerie.setText("Guardar");
        btGuardarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarSerieActionPerformed(evt);
            }
        });

        jLabel7.setText("Título");

        btEliminarSerie.setText("Eliminar");
        btEliminarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarSerieActionPerformed(evt);
            }
        });

        tfSerieTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSerieTituloActionPerformed(evt);
            }
        });

        btLimpiarSerie.setText("Limpiar");
        btLimpiarSerie.setToolTipText("");
        btLimpiarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarSerieActionPerformed(evt);
            }
        });

        jLabel9.setText("Temporadas");

        tfTemporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTemporadasActionPerformed(evt);
            }
        });

        jLabel10.setText("Episodios");
        jLabel10.setToolTipText("");

        jLabel11.setText("id");

        btCrearSerie.setText("Crear");
        btCrearSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearSerieActionPerformed(evt);
            }
        });

        jLabel13.setText("SERIE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfSerieTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTemporadas)
                            .addComponent(tfEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGuardarSerie)))
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tfSerieId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btCrearSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminarSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConsultarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btLimpiarSerie)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfSerieId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarSerie)
                    .addComponent(btCrearSerie)
                    .addComponent(btEliminarSerie)
                    .addComponent(btLimpiarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfSerieTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGuardarSerie)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        btConsultarSerie.getAccessibleContext().setAccessibleName("Consultar serie por id");

        jTabbedPane1.addTab("Serie", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEjecucion)
                .addGap(509, 509, 509))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Película");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearSerieActionPerformed
        // TODO add your handling code here:
        limpiarCamposParaCreacionSerie();
        
    }//GEN-LAST:event_btCrearSerieActionPerformed

    private void tfTemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTemporadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemporadasActionPerformed

    private void btLimpiarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarSerieActionPerformed
        // TODO add your handling code here:
        limpiarCamposSerie();
    }//GEN-LAST:event_btLimpiarSerieActionPerformed

    private void tfSerieTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSerieTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSerieTituloActionPerformed

    private void btEliminarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarSerieActionPerformed
        // TODO add your handling code here:
        if(!tfSerieId.getText().equals("")){
            eliminarSerie();
        }
    }//GEN-LAST:event_btEliminarSerieActionPerformed

    private void btGuardarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarSerieActionPerformed
        // TODO add your handling code here:
        crearSerie();
    }//GEN-LAST:event_btGuardarSerieActionPerformed

    private void btConsultarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSerieActionPerformed
        // TODO add your handling code here:
        if(!tfSerieId.getText().equals("")){
            buscarPorIdSerie();
            tfSerieId.setEnabled(true);
            
        }
    }//GEN-LAST:event_btConsultarSerieActionPerformed

    private void btCrearPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearPelActionPerformed
        limpiarCamposParaCreacionPel();
    }//GEN-LAST:event_btCrearPelActionPerformed

    private void tfPelDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPelDirectorActionPerformed

    }//GEN-LAST:event_tfPelDirectorActionPerformed

    private void btLimpiarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarPelActionPerformed
        limpiarCamposPel();
    }//GEN-LAST:event_btLimpiarPelActionPerformed

    private void tfPelTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPelTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPelTituloActionPerformed

    private void btEliminarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarPelActionPerformed
        if(!tfPelId.getText().equals("")){
            eliminarPel();
        }
    }//GEN-LAST:event_btEliminarPelActionPerformed

    private void btGuardarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarPelActionPerformed
        crearPel();
    }//GEN-LAST:event_btGuardarPelActionPerformed

    private void btConsultarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarPelActionPerformed
        if(!tfPelId.getText().equals("")){
            buscarPorIdPel();
            tfPelId.setEnabled(true);
        }
    }//GEN-LAST:event_btConsultarPelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarPel;
    private javax.swing.JButton btConsultarSerie;
    private javax.swing.JButton btCrearPel;
    private javax.swing.JButton btCrearSerie;
    private javax.swing.JButton btEliminarPel;
    private javax.swing.JButton btEliminarSerie;
    private javax.swing.JButton btGuardarPel;
    private javax.swing.JButton btGuardarSerie;
    private javax.swing.JButton btLimpiarPel;
    private javax.swing.JButton btLimpiarSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaResumen;
    private javax.swing.JLabel lbEjecucion;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfEpisodios;
    private javax.swing.JTextField tfPelDirector;
    private javax.swing.JTextField tfPelId;
    private javax.swing.JTextField tfPelTitulo;
    private javax.swing.JTextField tfSerieId;
    private javax.swing.JTextField tfSerieTitulo;
    private javax.swing.JTextField tfTemporadas;
    // End of variables declaration//GEN-END:variables

    
    //PELÍCULAS
    
    //setText es para mostrar el contenido de la variable en la ventana
    public void limpiarCamposParaCreacionPel(){
        tfPelId.setEnabled(false); //tfId es "Text field Id"
        btCrearPel.setEnabled(false);
        tfPelTitulo.setText("");
        tfPelDirector.setText("");
        jTextAreaResumen.setText("");
        tfAnio.setText("");
    }
    
    public void limpiarCamposPel(){
        tfPelId.setEnabled(true);
        btCrearPel.setEnabled(true);
        tfPelTitulo.setText("");
        tfPelDirector.setText("");
        jTextAreaResumen.setText("");
        tfAnio.setText("");
    }
    
    private void buscarPorIdPel() {
        Long id = Long.parseLong(tfPelId.getText().toString());
        Optional<Pelicula> optionalPelicula = peliculaRepositorio.findById(id);
        if(optionalPelicula.isPresent()){
            Pelicula pelicula = optionalPelicula.get();
            //para poder setear el texto, tengo que convertilo a string antes
            tfPelTitulo.setText(pelicula.getPelTitulo());
            tfPelDirector.setText(pelicula.getPelDirector());
            jTextAreaResumen.setText(pelicula.getPelResumen());
            tfAnio.setText(pelicula.getPelAnio());
        }
    }
    

    private void crearPel() {
        Pelicula pelicula = new Pelicula();
        pelicula.setPelTitulo(tfPelTitulo.getText());
        pelicula.setPelDirector(tfPelDirector.getText());
        pelicula.setPelResumen(jTextAreaResumen.getText());
        pelicula.setPelAnio(tfAnio.getText());

        Long id;
        //StringBuffer evita que se cree un nuevo objeto en memoria cada vez
        //que se actualiza el valor de una variable:
        //a = "";
        //a = 3 + 2 --> ¡Mala práctica!
        StringBuffer respuesta = new StringBuffer();
        if(tfPelId.getText().equals("")){
            id = null;
            respuesta.append("Se creó la película: ");
        }
        else{
            id = Long.parseLong(tfPelId.getText());
            respuesta.append("Se actualizó la película: ");
        }
         
       pelicula.setPelId(id);
                
        try{
            peliculaRepositorio.save(pelicula);
            respuesta.append(pelicula.getPelId());
            tfPelId.setText(pelicula.getPelId().toString());
            lbEjecucion.setText(respuesta.toString());
        }
        catch(Exception e)
        {
            lbEjecucion.setText("Ocurrio un error al guardar");
        }
       
    }
   
    //Eliminar un registro por Id
    public void eliminarPel(){
        Long id = Long.parseLong(tfPelId.getText());
        
        try{
            peliculaRepositorio.deleteById(id);
            lbEjecucion.setText("Se eliminó la pelicula: " + id.toString());
        }
        catch(Exception e)
        {
            lbEjecucion.setText("Ocurrio un error al eliminar");
        }
                
    }
    
    
    
    
    // ---------------SERIES----------------
    
      
    //setText es para mostrar el contenido de la variable en la ventana
    public void limpiarCamposParaCreacionSerie(){
        tfSerieId.setEnabled(false); //tfId es "Text field Id"
        btCrearSerie.setEnabled(false);
        tfSerieTitulo.setText("");
        tfTemporadas.setText("");
        tfEpisodios.setText("");
    }
    
    public void limpiarCamposSerie(){
        tfSerieId.setEnabled(true);
        btCrearSerie.setEnabled(true);
        tfSerieTitulo.setText("");
        tfTemporadas.setText("");
        tfEpisodios.setText("");
    }
    
    private void buscarPorIdSerie() {
        Long id = Long.parseLong(tfSerieId.getText());
        Optional<Serie> optionalSerie = serieRepositorio.findById(id);
        if(optionalSerie.isPresent()){
            Serie serie = optionalSerie.get();
            //para poder setear el texto, tengo que convertilo a string antes
            tfSerieTitulo.setText(serie.getSerTitulo());
            tfTemporadas.setText(serie.getSerTemporadas());
            tfEpisodios.setText(serie.getSerEpisodios());
        }
    }
    

    private void crearSerie() {
        Serie serie = new Serie();
        serie.setSerTitulo(tfSerieTitulo.getText());
        serie.setSerTemporadas(tfTemporadas.getText());
        serie.setSerEpisodios(tfEpisodios.getText());

        Long id;
        //StringBuffer evita que se cree un nuevo objeto en memoria cada vez
        //que se actualiza el valor de una variable:
        //a = "";
        //a = 3 + 2 --> ¡Mala práctica!
        StringBuffer respuesta = new StringBuffer();
        if(tfSerieId.getText().equals("")){
            id = null;
            respuesta.append("Se creó la serie: ");
        }
        else{
            id = Long.parseLong(tfSerieId.getText());
            respuesta.append("Se actualizó la serie: ");
        }
         
       serie.setSerId(id);
                
        try{
            serieRepositorio.save(serie);
            respuesta.append(serie.getSerId());
            tfSerieId.setText(serie.getSerId().toString());
            lbEjecucion.setText(respuesta.toString());
        }
        catch(Exception e)
        {
            lbEjecucion.setText("Ocurrio un error al guardar");
        }
       
    }
   
    //Eliminar un registro por Id
    public void eliminarSerie(){
        Long id = Long.parseLong(tfSerieId.getText());
        
        try{
            serieRepositorio.deleteById(id);
            lbEjecucion.setText("Se eliminó la serie: " + id.toString());
        }
        catch(Exception e)
        {
            lbEjecucion.setText("Ocurrio un error al eliminar");
        }
                
    }
}



